### ISSUE TITLE
click.php forbidden

### ISSUE THREAD

**Issue by joubertredrat** [piwikjapan/plugin-clickheat#3]
Hi, 

I tried to solve this problem using FAQ "What is "click.php returned a status code 403" ?" but doesn't work.

The problem is, on plugin folder have .htaccess blocking all and click.php works only if this .htaccess is removed or renamed, I tried to put .htaccess on lib and ClickHeat folder enabling access, but doesn't work too.

**Comment by joubertredrat** [comment]
Hi,

Solved, I saw here a htacess on repo, I tested with this and worked fine.

https://raw.githubusercontent.com/piwikjapan/plugin-clickheat/master/.htaccess

**Comment by piwikjapan** [comment]
Yes. I issued 0.1.4 with .htaccess, but automatic publish system (?) at marketplace does not understand .htaccess and marketplace doesn't distribute .htaccess...
