### ISSUE TITLE
piwik in https don't get site

### ISSUE THREAD

**Issue by joubertredrat** [piwikjapan/plugin-clickheat#5]
Hi guys,

My piwik is running with SSL and works fine with clickheat, the problem is to see data, if site target don't have ssl too, don't show site, only click map, then you need to enable on browser to show insecure files temporarily.

I know that isn't clickheat and piwik bug, but I think that is good idea to add this to FAQ

**Comment by piwikjapan** [comment]
Thank you for your feedback.
Yes. If Piwik works under https, you also should be used https for the target site. Because, ClickHeat uses iframe to put a heatmap on the target site.
